version: "3"
services:
    db:
      image: postgres
    web:
      build: .
      image: mydjango
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - migration
    migration:
      build: .
      image: mydjango-migration
      command: python manage.py migrate
      volumes:
        - .:/code
      depends_on:
        - db
